Repository lucas85235/CuberZ_Project, pull requests merged in 2020-02, with the labels that each got.

#19 Adicionado Script e Prefab de Level Manager
  CuberZ/Assets/-Game/Scripts/Character/Moster/LevelManager.meta
  CuberZ/Assets/-Game/Scripts/Character/Moster/LevelManager/Level Manager.prefab
  CuberZ/Assets/-Game/Scripts/Character/Moster/LevelManager/Level Manager.prefab.meta
  CuberZ/Assets/-Game/Scripts/Character/Moster/LevelManager/LevelManager.cs
  CuberZ/Assets/-Game/Scripts/Character/Moster/LevelManager/LevelManager.cs.meta
Labels: documentation

#28 Para a corrida ao pular
  CuberZ/Assets/-Game/Scripts/Character/Abtraction/MonsterBase.cs
Labels: enhancement

#35 Mofidy player animation character abstraction
  CuberZ/Assets/-Game/Models/Main-Character/Animations.meta
  CuberZ/Assets/-Game/Models/Main-Character/Animations/Player_BringBackMonster.anim
  CuberZ/Assets/-Game/Models/Main-Character/Animations/Player_BringBackMonster.anim.meta
  CuberZ/Assets/-Game/Models/Main-Character/Animations/Player_Empty.anim
  CuberZ/Assets/-Game/Models/Main-Character/Animations/Player_Empty.anim.meta
  CuberZ/Assets/-Game/Models/Main-Character/Animations/Player_FallJump.anim
  CuberZ/Assets/-Game/Models/Main-Character/Animations/Player_FallJump.anim.meta
  CuberZ/Assets/-Game/Models/Main-Character/Animations/Player_FastSwin.anim
  CuberZ/Assets/-Game/Models/Main-Character/Animations/Player_FastSwin.anim.meta
  CuberZ/Assets/-Game/Models/Main-Character/Animations/Player_Idle.anim
  CuberZ/Assets/-Game/Models/Main-Character/Animations/Player_Idle.anim.meta
  CuberZ/Assets/-Game/Models/Main-Character/Animations/Player_IdleJump.anim
  CuberZ/Assets/-Game/Models/Main-Character/Animations/Player_IdleJump.anim.meta
  CuberZ/Assets/-Game/Models/Main-Character/Animations/Player_IdleWater.anim
  CuberZ/Assets/-Game/Models/Main-Character/Animations/Player_IdleWater.anim.meta
  CuberZ/Assets/-Game/Models/Main-Character/Animations/Player_Run.anim
  CuberZ/Assets/-Game/Models/Main-Character/Animations/Player_Run.anim.meta
  CuberZ/Assets/-Game/Models/Main-Character/Animations/Player_SlowSwin.anim
  CuberZ/Assets/-Game/Models/Main-Character/Animations/Player_SlowSwin.anim.meta
  CuberZ/Assets/-Game/Models/Main-Character/Animations/Player_StartJump.anim
  CuberZ/Assets/-Game/Models/Main-Character/Animations/Player_StartJump.anim.meta
  CuberZ/Assets/-Game/Models/Main-Character/Animations/Player_ThrowCube.anim
  CuberZ/Assets/-Game/Models/Main-Character/Animations/Player_ThrowCube.anim.meta
  CuberZ/Assets/-Game/Models/Main-Character/Animations/Player_ThrowCubeNear.anim
  CuberZ/Assets/-Game/Models/Main-Character/Animations/Player_ThrowCubeNear.anim.meta
  CuberZ/Assets/-Game/Models/Main-Character/Animations/Player_Walk.anim
  CuberZ/Assets/-Game/Models/Main-Character/Animations/Player_Walk.anim.meta
  CuberZ/Assets/-Game/Models/Main-Character/Animators/Player-Animator.controller
  CuberZ/Assets/-Game/Models/Main-Character/Animators/_PlayerCaptureAnimator.controller
  CuberZ/Assets/-Game/Models/Main-Character/Animators/_PlayerCaptureAnimator.controller.meta
  CuberZ/Assets/-Game/Models/Main-Character/Animators/_PlayerJumpAnimator.controller
  CuberZ/Assets/-Game/Models/Main-Character/Animators/_PlayerJumpAnimator.controller.meta
  CuberZ/Assets/-Game/Models/Main-Character/Animators/_PlayerSwinAnimator.controller
  CuberZ/Assets/-Game/Models/Main-Character/Animators/_PlayerSwinAnimator.controller.meta
  CuberZ/Assets/-Game/Models/Main-Character/Animators/_PlayerWalkAnimator.controller
  CuberZ/Assets/-Game/Models/Main-Character/Animators/_PlayerWalkAnimator.controller.meta
  CuberZ/Assets/-Game/Models/Main-Character/Model/001.blend.meta
  CuberZ/Assets/-Game/Prefabs/Characters/PlayerReal.prefab
  CuberZ/Assets/-Game/Scenes/Game/Teste.unity
  CuberZ/Assets/-Game/Scripts/CaptureManager/CaptureSystem.cs
  CuberZ/Assets/-Game/Scripts/Character/Abtraction/CharacterAbstraction.cs
  CuberZ/Assets/-Game/Scripts/Character/Player/PlayerAnimation.cs
  CuberZ/Assets/-Game/Scripts/Character/Player/PlayerController.cs
Labels: documentation

#37 Adicionado HUD Kubber Team
  CuberZ/Assets/-Game/Prefabs/HUD/HUD Kubber Team.prefab
  CuberZ/Assets/-Game/Prefabs/HUD/HUD Kubber Team.prefab.meta
  CuberZ/Assets/-Game/Scripts/Hud/HUDKubberTeam.cs
  CuberZ/Assets/-Game/Scripts/Hud/HUDKubberTeam.cs.meta
Labels: documentation

#38 Adicionado NumericDamageEffect
  CuberZ/Assets/-Game/Prefabs/Effects.meta
  CuberZ/Assets/-Game/Prefabs/Effects/Numeric Damage Effect.prefab
  CuberZ/Assets/-Game/Prefabs/Effects/Numeric Damage Effect.prefab.meta
  CuberZ/Assets/-Game/Scripts/Effects.meta
  CuberZ/Assets/-Game/Scripts/Effects/NumericDamageEffect.cs
  CuberZ/Assets/-Game/Scripts/Effects/NumericDamageEffect.cs.meta
Labels: documentation

#36 Adicionado pegar e chamar Kubber
  CuberZ/Assets/-Game/Models/Main-Character/Model/001.blend.meta
  CuberZ/Assets/-Game/Prefabs/Characters/Enemys/002-Minite-Enemy.prefab
  CuberZ/Assets/-Game/Prefabs/Olds/001.prefab
  CuberZ/Assets/-Game/Scenes/Game/Teste.unity
  CuberZ/Assets/-Game/Scripts/CaptureManager/CaptureSystem.cs
  CuberZ/Assets/-Game/Scripts/Character/Abtraction/CharacterAbstraction.cs
  CuberZ/Assets/-Game/Scripts/Character/Abtraction/MonsterBase.cs
  CuberZ/Assets/-Game/Scripts/Character/Player/PlayerAnimation.cs
  CuberZ/Assets/-Game/Scripts/Character/Player/PlayerController.cs
Labels: enhancement

#42 BugFixed Animação do Miniti
  CuberZ/Assets/-Game/Scenes/Test-Scenes/Monsters/002-Minite.unity
  CuberZ/Assets/-Game/Scripts/Character/Moster/Specializations/MinitiBehaviuor.cs
Labels: bug

#45 BugFix Cube Collider
  CuberZ/Assets/-Game/Scenes/Game/Gameplay/Terrain/GamePlayer.asset
  CuberZ/Assets/-Game/Scenes/Game/Gameplay/Terrain/TerrainData_21c32464-42d1-4f03-bdaa-ba36d55f1de3.asset
  CuberZ/Assets/-Game/Scenes/Game/Gameplay/Terrain/TerrainData_21c32464-42d1-4f03-bdaa-ba36d55f1de3.asset.meta
  CuberZ/Assets/-Game/Scenes/Game/Gameplay/Terrain/TerrainData_4a561b0a-1fc8-4a28-bf1c-09c95c81d9fc.asset
  CuberZ/Assets/-Game/Scenes/Game/Gameplay/Terrain/TerrainData_4a561b0a-1fc8-4a28-bf1c-09c95c81d9fc.asset.meta
  CuberZ/Assets/-Game/Scenes/Game/Gameplay/Terrain/TerrainData_4c7dd739-09e2-49dd-b8dc-d2acf315b1d2.asset
  CuberZ/Assets/-Game/Scenes/Game/Gameplay/Terrain/TerrainData_4c7dd739-09e2-49dd-b8dc-d2acf315b1d2.asset.meta
  CuberZ/Assets/-Game/Scenes/Game/Gameplay/Terrain/TerrainData_ba540841-3244-46fb-bd12-b49710c2f2da.asset
  CuberZ/Assets/-Game/Scenes/Game/Gameplay/Terrain/TerrainData_ba540841-3244-46fb-bd12-b49710c2f2da.asset.meta
Labels: bug
